### ISSUE TITLE
panic: unable to load files

### ISSUE THREAD

**Issue by russelltg** [aptly-dev/aptly#1310]
Aptly crashed with the following in logs:

## Detailed Description

```
Jul 08 01:08:38 papt101ubu aptly[1678697]: openpgp: signing file 'Release'...
Jul 08 01:08:38 papt101ubu aptly[1678697]: openpgp: clearsigning file 'Release'...
Jul 08 01:08:50 papt101ubu aptly[1678697]: panic: unable to load files
Jul 08 01:08:50 papt101ubu aptly[1678697]: goroutine 843 [running]:
Jul 08 01:08:50 papt101ubu aptly[1678697]: github.com/aptly-dev/aptly/deb.(*PackageCollection).loadFiles(0xc003c0e858, 0x26?)
Jul 08 01:08:50 papt101ubu aptly[1678697]:         /__w/aptly/aptly/deb/package_collection.go:151 +0xf0
Jul 08 01:08:50 papt101ubu aptly[1678697]: github.com/aptly-dev/aptly/deb.(*Package).Files(0xc0122c9340)
Jul 08 01:08:50 papt101ubu aptly[1678697]:         /__w/aptly/aptly/deb/package.go:462 +0x3e
Jul 08 01:08:50 papt101ubu aptly[1678697]: github.com/aptly-dev/aptly/deb.(*PublishedRepoCollection).listReferencedFilesByComponent.func1(0xc000f83a00?)
Jul 08 01:08:50 papt101ubu aptly[1678697]:         /__w/aptly/aptly/deb/publish.go:1218 +0x5c
Jul 08 01:08:50 papt101ubu aptly[1678697]: github.com/aptly-dev/aptly/deb.(*PackageList).ForEach(0xc01460b350?, 0xc000f83b58)
Jul 08 01:08:50 papt101ubu aptly[1678697]:         /__w/aptly/aptly/deb/list.go:166 +0xac
Jul 08 01:08:50 papt101ubu aptly[1678697]: github.com/aptly-dev/aptly/deb.(*PublishedRepoCollection).listReferencedFilesByComponent(0xc00756cb40, {0x1c77910, 0x1}, {0xc008ec3c80, 0x4, 0x30?}, 0x20?, {0x14d27c8, 0xc007b0b530})
Jul 08 01:08:50 papt101ubu aptly[1678697]:         /__w/aptly/aptly/deb/publish.go:1212 +0x585
Jul 08 01:08:50 papt101ubu aptly[1678697]: github.com/aptly-dev/aptly/deb.(*PublishedRepoCollection).CleanupPrefixComponentFiles(0x13?, {0x1c77910, 0x1}, {0xc008ec3c80?, 0x4, 0x4}, {0x14d2598, 0xc000091660}, 0xc00046a8c0?, {0x14d27c8, ...})
Jul 08 01:08:50 papt101ubu aptly[1678697]:         /__w/aptly/aptly/deb/publish.go:1242 +0x1d1
Jul 08 01:08:50 papt101ubu aptly[1678697]: github.com/aptly-dev/aptly/api.apiPublishUpdateSwitch.func1({0x14d27c8, 0xc007b0b530}, 0x0?)
Jul 08 01:08:50 papt101ubu aptly[1678697]:         /__w/aptly/aptly/api/publish.go:357 +0x2d8
Jul 08 01:08:50 papt101ubu aptly[1678697]: github.com/aptly-dev/aptly/api.runTaskInBackground.func1({0x14d27c8?, 0xc007b0b530?}, 0x17?)
Jul 08 01:08:50 papt101ubu aptly[1678697]:         /__w/aptly/aptly/api/api.go:130 +0x12d
Jul 08 01:08:50 papt101ubu aptly[1678697]: github.com/aptly-dev/aptly/task.(*List).consumer.func1()
Jul 08 01:08:50 papt101ubu aptly[1678697]:         /__w/aptly/aptly/task/list.go:54 +0x47
Jul 08 01:08:50 papt101ubu aptly[1678697]: created by github.com/aptly-dev/aptly/task.(*List).consumer in goroutine 748
Jul 08 01:08:50 papt101ubu aptly[1678697]:         /__w/aptly/aptly/task/list.go:53 +0x26

```
## Your Environment

Ubuntu 22.04, `aptly version: '1.5.0+145+gb5bf2cbc`

I'm not exactly sure what was going on when it crashed.

**Comment by neolynx** [comment]
also here I think it s due to the fact that concurrent uploads to the same upload directory are happening ?

See: https://github.com/aptly-dev/aptly/issues/1305

**Comment by neolynx** [comment]
Aptly 1,6,0 has been released: https://github.com/aptly-dev/aptly/discussions/1414

I believe the issue is fixed, please reopen if it still persists...
