### ISSUE TITLE
Aptly panic on debian stretch / gpg issue

### ISSUE THREAD

**Issue by jgeysens** [aptly-dev/aptly#740]
## Detailed Description

With commit https://github.com/aptly-dev/aptly/commit/5a713534c6ced21c7ab08ab0de7028c8ba1d724d#diff-aa334e4d589f01da1799033e5aeedd69
aptly is not useable on Debian stretch, even if gpgv1 is installed.  I had to revert to version 1.2.0 to make aptly run on stretch.

## Context

```
panic: Couldn't find a suitable gpg executable. Make sure gnupg1 is available as either gpg or gpg1 in $PATH [recovered]
	panic: Couldn't find a suitable gpg executable. Make sure gnupg1 is available as either gpg or gpg1 in $PATH

goroutine 1 [running]:
github.com/aptly-dev/aptly/cmd.Run.func1(0xc4202f3f50)
	/Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/run.go:17 +0x131
panic(0xbe4aa0, 0xc42026e270)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/aptly-dev/aptly/pgp.NewGpgVerifier(0xc4202ca0c0)
	/Users/smira/Documents/go/src/github.com/aptly-dev/aptly/pgp/gnupg.go:178 +0x144
github.com/aptly-dev/aptly/context.(*AptlyContext).GetVerifier(0xc4202ca0c0, 0x0, 0x0)
	/Users/smira/Documents/go/src/github.com/aptly-dev/aptly/context/context.go:415 +0xd7
github.com/aptly-dev/aptly/cmd.aptlyRepoAdd(0xc4201b59e0, 0xc420269fe0, 0x2, 0x2, 0x1152680, 0xc42027cbe0)
	/Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/repo_add.go:23 +0x73
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc4201b59e0, 0xc420269fe0, 0x2, 0x2, 0xc4202f3e01, 0xc4202f3e18)
	/Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:305 +0x2a7
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc42026a900, 0xc420269fd0, 0x3, 0x3, 0xc420000101, 0xd0f3c0)
	/Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:283 +0x151
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc420270b40, 0xc420269fc0, 0x4, 0x4, 0xc420277340, 0xc420269fc0)
	/Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:283 +0x151
github.com/aptly-dev/aptly/cmd.Run(0xc420270b40, 0xc42000e150, 0x4, 0x4, 0xc420237401, 0x0)
	/Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/run.go:41 +0x12a
main.main()
	/Users/smira/Documents/go/src/github.com/aptly-dev/aptly/main.go:24 +0x151
```

## Your Environment
Installed packages 

```
ii  gpgv                            2.1.18-8~deb9u1                amd64        GNU privacy guard - signature verification tool
ii  gpgv1                           1.4.21-4                       amd64        GNU privacy guard - signature verification tool (deprecated "classic" version)

```

**Comment by apachelogger** [comment]
The panic tells you that gpg1 isn't available...

https://www.aptly.info/doc/feature/pgp-providers/

> On newer Debian systems you’ll want to make sure that the gnupg1 and gpgv1 packages are installed.

**Comment by igorpecovnik** [comment]
The same problem and workaround persist on Ubuntu Bionic.

**Comment by terentev-mn** [comment]
`apt install gpgv1 gpgv2 gnupg1`

**Comment by smira** [comment]
aptly latest version (nightly builds) works with both GPG1 and GPG2.

**Comment by ekristen** [comment]
MacOS seems to be broken too. I tried to install the latest commit but it doens't work either.

**Comment by smira** [comment]
@ekristen what is the error message you see?

**Comment by ekristen** [comment]
Can’t find a suitable gpg install. 

It’s definitely caused partially by the regex which doesn’t take into account gpg for MacOS (GnuPG/MacGPG2) 2.2.10

I also think that it will fail because it’s not 2.0.xxx
