### ISSUE TITLE
aptly fails to find gpg and panics

### ISSUE THREAD

**Issue by soupdiver** [aptly-dev/aptly#823]
## Detailed Description
aptly fails to find/detect gpg
I'm aware that aptly officially only supports gnupg 1.x
However, according to #743 I can set the environment variable `APTLY_SKIP_GPG_VERSION_CHECK` to make it work with gnupg 2.x

I'm running inside an Alpine Linux Docker container, because this is part of my CI pipeline.
`aptly` seems to fail to find `gpg` at all, even if it's inside $PATH and can easily be execute via CLI.

Seems similar to #740 

## Your Environment
`aptly version: 1.3.0`
```
gpg --version
gpg (GnuPG) 2.2.12
libgcrypt 1.8.4
```
```
which gpg
/usr/bin/gpg
```
```
echo $APTLY_SKIP_GPG_VERSION_CHECK
1
```
## Actual error
```
aptly publish repo -distribution "cosmic" foobz
Warning: publishing from empty source, architectures list should be complete, it can't be changed after publishing (use -architectures flag)
panic: Couldn't find a suitable gpg executable. Make sure gnupg1 is available as either gpg or gpg1 in $PATH [recovered]
        panic: Couldn't find a suitable gpg executable. Make sure gnupg1 is available as either gpg or gpg1 in $PATH

goroutine 1 [running]:
github.com/aptly-dev/aptly/cmd.Run.func1(0xc420105f50)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/run.go:17 +0x131
panic(0xbe4aa0, 0xc420045fb0)
        /usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/aptly-dev/aptly/pgp.NewGpgSigner(0xc420010240)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/pgp/gnupg.go:121 +0xba
github.com/aptly-dev/aptly/context.(*AptlyContext).GetSigner(0xc420010240, 0x0, 0x0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/context/context.go:403 +0xd7
github.com/aptly-dev/aptly/cmd.getSigner(0xc420287500, 0xc420287500, 0x0, 0xf, 0x11c0820)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/publish.go:14 +0x7e
github.com/aptly-dev/aptly/cmd.aptlyPublishSnapshotOrRepo(0xc420280c60, 0xc42027f5e0, 0x1, 0x2, 0x1152680, 0xc4201b3600)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/publish_snapshot.go:150 +0xdf7
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc420280c60, 0xc42027f5e0, 0x1, 0x2, 0xc42027de01, 0xc42027de18)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:305 +0x2a7
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc420281200, 0xc42027f5d0, 0x2, 0x3, 0xc420000101, 0xd0f3c0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:283 +0x151
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc4202819e0, 0xc42027f5c0, 0x3, 0x4, 0xc420287500, 0xc42027f5c0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:283 +0x151
github.com/aptly-dev/aptly/cmd.Run(0xc4202819e0, 0xc42000e0d0, 0x5, 0x5, 0xc420208001, 0x0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/run.go:41 +0x12a
main.main()
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/main.go:24 +0x151
```

**Comment by soupdiver** [comment]
Ah I just noticed that #743 was merged _after_ `1.3` release 😐 
Will try with nightly and close in case

**Comment by soupdiver** [comment]
Ok, tired latest `master` and it seems to work

**Comment by lazouz** [comment]
okay, so we'll use 1.2.0 until 1.4.0 is out ?

**Comment by soupdiver** [comment]
@lazouz I guess either this or use a nightly build as I did.

**Comment by dankegel** [comment]
This bit me.  Ouch, ouch, ouch.
